config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  devise_scope :user do
    get "users/registrations/complete" => "users/registrations#complete"
  end

  resource :user_information
  resource :user_mobile_phone, only: %i[new create] do
    collection do
      get :verification
      post :verification
    end
  end
  resources :items do
    resources :favorites, only: %i[create destroy], shallow: true
    delete "favorites", to: "favorites#destroy", as: :favorite
    resources :comments, only: %i[create destroy], shallow: true do
      resources :reports, only: %i[new create]
    end
    resources :stripe_payments, only: %i[index new destroy]
    get "stripe_payments/create" => "stripe_payments#create", as: :get_create_stripe_payments
    resource :current_stripe_payment, only: %i[update]
    resources :shipping_addresses
    resource :current_shipping_address, only: %i[update]
    resources :orders, only: %i[new create show], shallow: true do
      resources :messages, only: %i[create]
      member do
        post :ship
      end
      resource :payer_evaluation, only: %i[create]
      resource :seller_evaluation, only: %i[create]
    end
  end

  resources :users, only: %i[show] do
    resources :evaluations, only: %i[index]
  end
  
  get "mypage" => "mypage#index"
  namespace :mypage do
    resources :favorites, only: %i[index destroy]
    resources :items, only: %i[index]
    namespace :items do
      get "in_progress" => "in_progress#index", as: :in_progress
      get "completed" => "completed#index", as: :completed
    end
  end

  resources :notifications, only: %i[index show]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :user_id, uniqueness: { scope: :item_id }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  
  def create
  end

  def destroy
  end
end

app/controllers/mypage/favorites_controller.rb
class Mypage::FavoritesController < ApplicationController
  layout "mypage"
  before_action :authenticate_user!

  def index
  end

  def destroy
    favorite = current_user.favorites.find(params[:id])

    favorite.destroy

    redirect_to mypage_favorites_path, notice: "いいねを削除しました"
  end
end

app/controllers/mypage/items/completed_controller.rb
class Mypage::Items::CompletedController < ApplicationController
  layout "mypage"
  before_action :authenticate_user!

  def index
    @items =
      current_user
        .items
        .joins(:order)
        .merge(Order.completed)    
  end
end

app/controllers/mypage/items/in_progress_controller.rb
class Mypage::Items::InProgressController < ApplicationController
  layout 'mypage'
  before_action :authenticate_user!

  def index
    @items =
      current_user
        .items
        .joins(:order)
        .merge(Order.not_completed)
  end
end

app/controllers/mypage/items_controller.rb
class Mypage::ItemsController < ApplicationController
  layout "mypage"
  before_action :authenticate_user!

  def index
    @items =
      current_user
        .items
        .left_joins(:order)
        .where(order: { id: nil })
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/views/mypage/favorites/index.html.erb
<div class="w-full md:w-9/12" id="products">
  <div class="mb-2">
    <h3 class="font-black text-lg mb-4 text-center md:text-2xl md:text-left">いいね！した商品</h3>
  </div>
  <ul class="border-t border-gray-300">
    <% current_user.favorites.each do |favorite| %>
      <li class="border-b border-gray-300 px-2 group md:px-4 hover:bg-gray-100 duration-200 ">
        <div class="flex">
          <div class="flex-grow">
            <%= link_to item_path(favorite.item), class: "py-4 flex group space-x-4 md:space-x-4" do %>
              <div class="w-24 h-24 bg-gray-200 flex justify-center items-center relative flex-shrink-0 overflow-hidden rounded-md">
                <% if favorite.item.order %>
                  <div class="w-16 h-16 font-bold bg-red-500 text-white absolute z-10 rotate-45 flex items-end justify-center right-0 top-0 text-[0.6rem] md:text-[4px] pb-0.5 -mr-8 -mt-8">SOLD</div>
                <% end %>
                <%= image_tag favorite.item.images.first.url, class: "object-contain h-full" %>
              </div>
              <div class="flex-grow">
                <p class="text-base mb-1 md:text-lg"><%= favorite.item.name %></p>
                <p class="text-sm font-bold mb-1"><%= number_to_currency(favorite.item.price) %></p>
                <ul class="flex space-x-4 items-center text-gray-700">
                  <li class="flex items-center space-x-0.5">
                    <svg class="w-4" viewbox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                      <!-- Generator: Sketch 59.1 (86144) - https://sketch.com-->
                      <g id="🔍-Product-Icons" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <g id="ic_fluent_heart_24_regular" fill="currentColor" fill-rule="nonzero">
                          <path d="M12.8198687,5.57958759 L11.9991485,6.40209417 L11.1758977,5.57884333 C9.07682963,3.47977526 5.67356786,3.47977526 3.5744998,5.57884333 C1.47543173,7.6779114 1.47543173,11.0811732 3.5744998,13.1802412 L11.4698687,21.0756101 C11.7627619,21.3685033 12.2376356,21.3685033 12.5305288,21.0756101 L20.4319958,13.1787767 C22.5263889,11.0727481 22.5299763,7.6790351 20.4305288,5.57958759 C18.3276384,3.4766972 14.9227559,3.47670037 12.8198687,5.57958759 Z M19.3684016,12.1210587 L12.0001987,19.4846198 L4.63515997,12.1195811 C3.12187834,10.6062994 3.12187834,8.15278513 4.63515997,6.6395035 C6.1484416,5.12622187 8.60195589,5.12622187 10.1152375,6.6395035 L11.4726817,7.99694767 C11.7705471,8.2948131 12.2552416,8.28900906 12.545889,7.98409641 L13.8805288,6.64024776 C15.3976301,5.12314654 17.8527652,5.12314425 19.3698687,6.64024776 C20.8835151,8.15389424 20.8809293,10.6001281 19.3684016,12.1210587 Z" id="🎨-Color"></path>
                        </g>
                      </g>
                    </svg>
                    <span class="text-xs"><%= favorite.item.favorites.size %></span>
                  </li>
                  <li class="flex items-center space-x-0.5">
                    <svg class="w-4" fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                      <path d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10a9.96 9.96 0 0 1-4.587-1.112l-3.826 1.067a1.25 1.25 0 0 1-1.54-1.54l1.068-3.823A9.96 9.96 0 0 1 2 12C2 6.477 6.477 2 12 2Zm0 1.5A8.5 8.5 0 0 0 3.5 12c0 1.47.373 2.883 1.073 4.137l.15.27-1.112 3.984 3.987-1.112.27.15A8.5 8.5 0 1 0 12 3.5ZM8.75 13h4.498a.75.75 0 0 1 .102 1.493l-.102.007H8.75a.75.75 0 0 1-.102-1.493L8.75 13h4.498H8.75Zm0-3.5h6.505a.75.75 0 0 1 .101 1.493l-.101.007H8.75a.75.75 0 0 1-.102-1.493L8.75 9.5h6.505H8.75Z" fill="currentColor"></path>
                    </svg>
                    <span class="text-xs"><%= favorite.item.comments.size %></span>
                  </li>
                </ul>
              </div>
            <% end %>
          </div>
          <div class="flex items-center justify-center">
            <%= link_to "削除", mypage_favorite_path(favorite), method: :delete, data: { confirm: "本当に削除しますか？"}, class: "bg-white border-2 border-red-500 font-bold text-red-500 px-4 py-1 rounded text-base" %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>