config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  devise_scope :user do
    get "users/registrations/complete" => "users/registrations#complete"
  end

  resource :user_information
  resource :user_mobile_phone, only: %i[new create] do
    collection do
      get :verification
      post :verification
    end
  end
  resources :items do
    resources :favorites, only: %i[create destroy], shallow: true
    delete "favorites", to: "favorites#destroy", as: :favorite
    resources :comments, only: %i[create destroy], shallow: true do
      resources :reports, only: %i[new create]
    end
    resources :stripe_payments, only: %i[index new destroy]
    get "stripe_payments/create" => "stripe_payments#create", as: :get_create_stripe_payments
    resource :current_stripe_payment, only: %i[update]
    resources :shipping_addresses
    resource :current_shipping_address, only: %i[update]
    resources :orders, only: %i[new create show], shallow: true do
      resources :messages, only: %i[create]
      member do
        post :ship
      end
      resource :payer_evaluation, only: %i[create]
      resource :seller_evaluation, only: %i[create]
    end
  end

  resources :users, only: %i[show] do
    resources :evaluations, only: %i[index]
  end
  
  get "mypage" => "mypage#index"
  namespace :mypage do
    resources :favorites, only: %i[index destroy]
    resources :items, only: %i[index]
    namespace :items do
      get "in_progress" => "in_progress#index", as: :in_progress
      get "completed" => "completed#index", as: :completed
    end
  end

  resources :notifications, only: %i[index show]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
    <div class="bg-red-100 booder-t border-t border-red-100 text-red-700 px-4 py-3" role="alert">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_evaluation.html.erb
<div class="flex space-x-4 items-center">
  <%= link_to user_evaluations_path(user), class: "flex space-x-2 items-center text-blue-500" do %>
    <ul class="flex items-center space-x-0.5" id="stars">
      <% user.evaluation_rate.times do %>
        <li>
          <svg class="text-yellow-500 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 13 12">
            <path d="M6.5,9.644,10.517,12,9.451,7.56,13,4.573,8.326,4.187,6.5,0,4.674,4.187,0,4.573,3.549,7.56,2.483,12Z" fill="currentColor"></path>
          </svg>
        </li>
      <% end %>
      <% (User::EVALUATION_MAX_RATE - user.evaluation_rate).times do %>
        <li>
          <svg class="text-gray-200 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 13 12">
            <path d="M6.5,9.644,10.517,12,9.451,7.56,13,4.573,8.326,4.187,6.5,0,4.674,4.187,0,4.573,3.549,7.56,2.483,12Z" fill="currentColor"></path>
          </svg>
        </li>
      <% end %>
    </ul>
    <span class="text-sm"><%= user.evaluations.count %></span>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-gray-800 w-full">
  <div class="mx-auto py-12 md:flex w-9/12">
    <ul class="text-white flex flex-col space-y-2 mb-4 md:w-1/3">
      <li class="font-black">URIKAIについて</li>
      <li><a class="text-sm opacity-75 underline" href="#">会社概要</a></li>
      <li><a class="text-sm opacity-75 underline" href="#">採用情報</a></li>
      <li><a class="text-sm opacity-75 underline" href="#">プレスリリース</a></li>
    </ul>
    <ul class="text-white flex flex-col space-y-2 mb-4 md:w-1/3">
      <li class="font-black">ヘルプと各種情報</li>
      <li><a class="text-sm opacity-75 underline" href="#">ガイド</a></li>
      <li><a class="text-sm opacity-75 underline" href="#">ウリカイあんしん宣言</a></li>
      <li><a class="text-sm opacity-75 underline" href="#">お問い合わせ</a></li>
    </ul>
    <ul class="text-white flex flex-col space-y-2 mb-4 md:w-1/3">
      <li class="font-black">プライバシーと利用規約</li>
      <li><a class="text-sm opacity-75 underline" href="#">プライバシー</a></li>
      <li><a class="text-sm opacity-75 underline" href="#">利用規約</a></li>
      <li><a class="text-sm opacity-75 underline" href="#">特定商取引に関する表記</a></li>
    </ul>
  </div>
  <div class="w-full bg-gray-900 text-center py-4 text-white">
    <div class="flex items-center justify-center"><%= image_tag "logo_white.svg", class: "w-6 mr-1" %><span class="inline p-0">URIKAI</span></div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="h-16 fixed z-40 bg-white top-0 w-full px-4 py-2 flex jusity-between items-center border-b border-gray-300 md:px-10">
  <button class="flex  rounded-full w-10 h-10 md:hidden items-center justify-center hover:bg-gray-100 duration-200 trantision">
    <svg class="w-8" width="24" height="24" fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
      <path d="M15.707 4.293a1 1 0 0 1 0 1.414L9.414 12l6.293 6.293a1 1 0 0 1-1.414 1.414l-7-7a1 1 0 0 1 0-1.414l7-7a1 1 0 0 1 1.414 0Z" fill="currentColor"></path>
    </svg>
  </button>
  <div class="flex items-center space-x-6 w-full md:w-auto  justify-center md:jusify-start">
    <a class="block flex items-centrer text-xl h-12 justify-center _mx-auto md:ml-0 " href="/">
      <svg class="text-red-500 mr-1.5 w-7" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewbox="0 0 512 512" xml:space="preserve">
        <g>
          <path d="M454.002,324.104V187.896c16.877-5.176,29.228-20.691,29.228-39.268c0-22.79-18.475-41.257-41.258-41.257            c-10.87,0-20.69,4.292-28.06,11.168L296.125,50.53c0.689-2.991,1.136-6.069,1.136-9.272C297.261,18.468,278.786,0,256.004,0            c-22.782,0-41.258,18.468-41.258,41.258c0,3.203,0.447,6.281,1.136,9.272L98.087,118.54c-7.37-6.876-17.191-11.168-28.062-11.168            c-22.782,0-41.256,18.467-41.256,41.257c0,18.576,12.351,34.091,29.227,39.268v136.208c-16.876,5.176-29.227,20.691-29.227,39.268            c0,22.79,18.474,41.257,41.256,41.257c10.879,0,20.692-4.292,28.062-11.168l117.787,68.01c-0.69,2.991-1.136,6.069-1.136,9.272            c0,22.79,18.475,41.258,41.257,41.258s41.257-18.468,41.257-41.258c0-3.203-0.446-6.288-1.136-9.28l117.788-68.002            c7.37,6.876,17.191,11.168,28.068,11.168c22.783,0,41.258-18.467,41.258-41.257C483.231,344.795,470.879,329.28,454.002,324.104z            M243.967,431.476c-6.054,1.856-11.52,4.965-16.031,9.178l-117.788-68.01c0.689-2.992,1.136-6.077,1.136-9.272            c0-18.576-12.351-34.091-29.228-39.268V187.896c6.054-1.856,11.521-4.965,16.032-9.178l117.787,68.009            c-0.69,2.992-1.136,6.07-1.136,9.273c0,18.576,12.35,34.091,29.228,39.268V431.476z M227.935,225.91l-117.788-68.009            c0.689-2.992,1.136-6.07,1.136-9.273c0-3.203-0.447-6.281-1.136-9.272l117.796-68.01c7.369,6.876,17.19,11.168,28.06,11.168            c10.87,0,20.691-4.292,28.061-11.168l117.787,68.01c-0.689,2.992-1.136,6.069-1.136,9.272c0,3.196,0.447,6.281,1.136,9.273            l-117.803,68.002c-7.37-6.869-17.182-11.16-28.053-11.16S235.305,219.034,227.935,225.91z M429.943,324.104            c-16.877,5.176-29.227,20.691-29.227,39.268c0,3.195,0.447,6.281,1.136,9.272l-117.795,68.01            c-4.519-4.214-9.978-7.323-16.031-9.178V295.268c16.877-5.177,29.227-20.692,29.227-39.268c0-3.203-0.446-6.281-1.136-9.273            l117.796-68.009c4.511,4.214,9.977,7.323,16.031,9.178V324.104z" fill="currentColor"></path>
        </g>
      </svg>
      <div class="flex-0 h-full flex items-center">URIKAI</div>
    </a>
    <div class="w-full ml-2 relative w-64 hidden md:flex">
      <input class="border border-gray-300 w-full bg-gray-100 h-10 px-5 pr-10 rounded text-sm border-gray-200 focus:outline-none" type="search" name="serch" placeholder="何をお探しですか？">
      <button class="absolute right-0 top-0 mt-3 mr-4" type="submit">
        <svg class="h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" viewbox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve" width="512px" height="512px">
          <path d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z"></path>
        </svg>
      </button>
    </div>
  </div>
  <div class="text-right justify-end md:flex-grow mt-5 mr-5 md:mt-0 md:mr-0 absolute top-0 right-0 md:static md:flex">
    <!--SP用ヘッダーメニュー-->
    <ul class="flex items-center space-x-4 text-sm flex md:hidden">
      <li class="relative">
        <button class="h-6 w-6 flex items-center justify-center rounded-full hover:bg-gray-100 duration-200">
          <svg class="h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" viewbox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve" width="512px" height="512px">
            <path d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z"></path>
          </svg>
        </button>
      </li>
      <li class="relative"><span class="absolute top-0 right-0 bg-red-500 rounded-full text-white text-xs font-bold flex items-center justify-center h-4 py-0.5 px-1 min-w-[1rem] -mt-2 -mr-2">44</span>
        <button class="h-6 w-6 flex items-center justify-center rounded-full hover:bg-gray-100 duration-200">
          <svg class="w-4 h-4" viewbox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <!-- Generator: Sketch 59.1 (86144) - https://sketch.com-->
            <title>ic_fluent_checkmark_24_filled</title>
            <desc>Created with Sketch.</desc>
            <g id="🔍-Product-Icons" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
              <g id="ic_fluent_checkmark_24_filled" fill="currentColor" fill-rule="nonzero">
                <path d="M8.5,16.5857864 L4.70710678,12.7928932 C4.31658249,12.4023689 3.68341751,12.4023689 3.29289322,12.7928932 C2.90236893,13.1834175 2.90236893,13.8165825 3.29289322,14.2071068 L7.79289322,18.7071068 C8.18341751,19.0976311 8.81658249,19.0976311 9.20710678,18.7071068 L20.2071068,7.70710678 C20.5976311,7.31658249 20.5976311,6.68341751 20.2071068,6.29289322 C19.8165825,5.90236893 19.1834175,5.90236893 18.7928932,6.29289322 L8.5,16.5857864 Z" id="🎨-Color"></path>
              </g>
            </g>
          </svg>
        </button>
      </li>
    </ul>
    <!--PC用ヘッダーメニュー-->
    <ul class="flex items-center space-x-4 text-sm hidden md:flex">
      <li>
        <%= link_to "お知らせ", notifications_path, class: "relative hover:bg-gray-100 duration-200 rounded-lg px-2 py-2" %>
      </li>
      <% if user_signed_in? %>
        <li><%= link_to "マイページ", mypage_path, class: "relative hover:bg-gray-100 duration-200 rounded-lg px-2 py-2" %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "本当にログアウトしますか?" }, class: "relative hover:bg-gray-100 duration-200 rounded-lg px-2 py-2" %></li>
      <% else %>
        <li><%= link_to "ログイン", new_user_session_path, class: "relative hover:bg-gray-100 duration-200 rounded-lg px-2 py-2" %></li>
        <li><%= link_to "会員登録", new_user_registration_path, class: "relative hover:bg-gray-100 duration-200 rounded-lg px-2 py-2" %></li>
      <% end %>
      <li>
        <%= link_to "出品", new_item_path, class: "bg-red-500 font-bold text-white px-4 py-1 rounded text-base" %>
      </li>
    </ul>
  </div>
</header>

app/views/shared/_profile.html.erb
<div id="profile">
  <div class="flex space-x-4 items-start mb-4 md:items-center">
    <%= image_tag "profile.png", class: "rounded-full w-16 h-16 md:w-24 md:h-24" %>
    <div>
      <p class="font-bold"><%= user.nickname %></p>
      <%= render partial: "shared/evaluation", locals: { user: user } %>
      <button class="border text-sm border-red-500 text-red-500 px-4 py-1 rounded-md w-full md:w-auto mt-2 md:mt-0">＋フォロー</button>
    </div>
  </div>
  <div class="flex space-x-4 items-start md:items-center">
    <dl class="text-sm flex space-x-2">
      <dt class="font-bold"><%= user.items.size %></dt>
      <dd>出品数</dd>
    </dl>
    <dl class="text-sm flex space-x-2">
      <dt class="font-bold">12</dt>
      <dd>フォロワー</dd>
    </dl>
    <dl class="text-sm flex space-x-2">
      <dt class="font-bold">4</dt>
      <dd>フォロー中</dd>
    </dl>
  </div>
</div>