config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  devise_scope :user do
    get "users/registrations/complete" => "users/registrations#complete"
  end

  resource :user_information
  resource :user_mobile_phone, only: %i[new create] do
    collection do
      get :verification
      post :verification
    end
  end
  resources :items do
    resources :favorites, only: %i[create destroy], shallow: true
    delete "favorites", to: "favorites#destroy", as: :favorite
    resources :comments, only: %i[create destroy], shallow: true do
      resources :reports, only: %i[new create]
    end
    resources :stripe_payments, only: %i[index new destroy]
    get "stripe_payments/create" => "stripe_payments#create", as: :get_create_stripe_payments
    resource :current_stripe_payment, only: %i[update]
    resources :shipping_addresses
    resource :current_shipping_address, only: %i[update]
    resources :orders, only: %i[new create show], shallow: true do
      resources :messages, only: %i[create]
      member do
        post :ship
      end
      resource :payer_evaluation, only: %i[create]
      resource :seller_evaluation, only: %i[create]
    end
  end

  resources :users, only: %i[show] do
    resources :evaluations, only: %i[index]
  end
  
  get "mypage" => "mypage#index"
  namespace :mypage do
    resources :favorites, only: %i[index destroy]
    resources :items, only: %i[index]
    namespace :items do
      get "in_progress" => "in_progress#index", as: :in_progress
      get "completed" => "completed#index", as: :completed
    end
  end

  resources :notifications, only: %i[index show]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :item_category
  belongs_to :item_condition
  belongs_to :shipping_payer_type
  belongs_to :prefecture
  belongs_to :shipping_day_type

  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one :order, dependent: :restrict_with_error

  validates :images, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true

  mount_uploaders :images, ImageUploader
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_current_user_item, only: [:edit, :update]
  before_action :check_order, only: %i[edit update]

  def new
    @item = current_user.items.build
  end

  def create
    @item = current_user.items.build(item_params)

    if @item.save
      redirect_to @item, notice: "商品の作成に成功しました"
    else
      flash.now.alert = "商品の作成に失敗しました"
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item), notice: "商品の更新に成功しました"
    else
      flash.now.alert = "商品の更新に失敗しました"
      render :edit
    end
  end

  def destroy
  end

  private

  def item_params
    params.require(:item).permit(
      :item_category_id,
      :item_condition_id,
      :name,
      :description,
      :shipping_payer_type_id,
      :prefecture_id,
      :shipping_day_type_id,
      :price,
      :images_cache,
      images: []
    )
  end

  def set_current_user_item
    @item = current_user.items.find(params[:id])
  end

  def check_order
    if @item.order
      redirect_to item_path(@item), alert: "商品は購入済のため編集できません"
    end
  end
end

app/controllers/mypage/favorites_controller.rb
class Mypage::FavoritesController < ApplicationController
  layout "mypage"
  before_action :authenticate_user!

  def index
  end

  def destroy
    favorite = current_user.favorites.find(params[:id])

    favorite.destroy

    redirect_to mypage_favorites_path, notice: "いいねを削除しました"
  end
end

app/controllers/mypage/items/completed_controller.rb
class Mypage::Items::CompletedController < ApplicationController
  layout "mypage"
  before_action :authenticate_user!

  def index
    @items =
      current_user
        .items
        .joins(:order)
        .merge(Order.completed)    
  end
end

app/controllers/mypage/items/in_progress_controller.rb
class Mypage::Items::InProgressController < ApplicationController
  layout 'mypage'
  before_action :authenticate_user!

  def index
    @items =
      current_user
        .items
        .joins(:order)
        .merge(Order.not_completed)
  end
end

app/controllers/mypage/items_controller.rb
class Mypage::ItemsController < ApplicationController
  layout "mypage"
  before_action :authenticate_user!

  def index
    @items =
      current_user
        .items
        .left_joins(:order)
        .where(order: { id: nil })
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/views/mypage/items/_items.html.erb
<% if items.exists? %>
  <ul class="border-t border-gray-300">
    <% items.each do |item| %>
      <li class="border-b border-gray-300 px-2 group md:px-4 hover:bg-gray-100 duration-200 ">
        <%= link_to item_path(item), class: "py-4 flex group space-x-4 md:space-x-4" do %>
          <div class="w-24 h-24 bg-gray-200 flex justify-center items-center relative flex-shrink-0 overflow-hidden rounded-md">
            <% if item.order %>
              <div class="w-16 h-16 font-bold bg-red-500 text-white absolute z-10 rotate-45 flex items-end justify-center right-0 top-0 text-[0.6rem] md:text-[4px] pb-0.5 -mr-8 -mt-8">SOLD</div>
            <% end %>
            <%= image_tag item.images.first.url, class: "object-contain h-full" %>
          </div>
          <div class="flex-grow">
            <p class="text-base mb-1 md:text-lg"><%= item.name %></p>
            <p class="text-sm font-bold mb-1"><%= number_to_currency(item.price) %></p>
            <ul class="flex space-x-4 items-center text-gray-700">
              <li class="flex items-center space-x-0.5">
                <svg class="w-4" viewbox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                  <!-- Generator: Sketch 59.1 (86144) - https://sketch.com-->
                  <g id="🔍-Product-Icons" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                    <g id="ic_fluent_heart_24_regular" fill="currentColor" fill-rule="nonzero">
                      <path d="M12.8198687,5.57958759 L11.9991485,6.40209417 L11.1758977,5.57884333 C9.07682963,3.47977526 5.67356786,3.47977526 3.5744998,5.57884333 C1.47543173,7.6779114 1.47543173,11.0811732 3.5744998,13.1802412 L11.4698687,21.0756101 C11.7627619,21.3685033 12.2376356,21.3685033 12.5305288,21.0756101 L20.4319958,13.1787767 C22.5263889,11.0727481 22.5299763,7.6790351 20.4305288,5.57958759 C18.3276384,3.4766972 14.9227559,3.47670037 12.8198687,5.57958759 Z M19.3684016,12.1210587 L12.0001987,19.4846198 L4.63515997,12.1195811 C3.12187834,10.6062994 3.12187834,8.15278513 4.63515997,6.6395035 C6.1484416,5.12622187 8.60195589,5.12622187 10.1152375,6.6395035 L11.4726817,7.99694767 C11.7705471,8.2948131 12.2552416,8.28900906 12.545889,7.98409641 L13.8805288,6.64024776 C15.3976301,5.12314654 17.8527652,5.12314425 19.3698687,6.64024776 C20.8835151,8.15389424 20.8809293,10.6001281 19.3684016,12.1210587 Z" id="🎨-Color"></path>
                    </g>
                  </g>
                </svg>
                <span class="text-xs"><%= item.favorites.size %></span>
              </li>
              <li class="flex items-center space-x-0.5">
                <svg class="w-4" fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10a9.96 9.96 0 0 1-4.587-1.112l-3.826 1.067a1.25 1.25 0 0 1-1.54-1.54l1.068-3.823A9.96 9.96 0 0 1 2 12C2 6.477 6.477 2 12 2Zm0 1.5A8.5 8.5 0 0 0 3.5 12c0 1.47.373 2.883 1.073 4.137l.15.27-1.112 3.984 3.987-1.112.27.15A8.5 8.5 0 1 0 12 3.5ZM8.75 13h4.498a.75.75 0 0 1 .102 1.493l-.102.007H8.75a.75.75 0 0 1-.102-1.493L8.75 13h4.498H8.75Zm0-3.5h6.505a.75.75 0 0 1 .101 1.493l-.101.007H8.75a.75.75 0 0 1-.102-1.493L8.75 9.5h6.505H8.75Z" fill="currentColor"></path>
                </svg><span class="text-xs"><%= item.comments.size %></span>
              </li>
            </ul>
          </div>
          <div class="flex items-center justify-center">
            <svg class="w-5" viewbox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M8.46967 4.21967C8.17678 4.51256 8.17678 4.98744 8.46967 5.28033L15.1893 12L8.46967 18.7197C8.17678 19.0126 8.17678 19.4874 8.46967 19.7803C8.76256 20.0732 9.23744 20.0732 9.53033 19.7803L16.7803 12.5303C17.0732 12.2374 17.0732 11.7626 16.7803 11.4697L9.53033 4.21967C9.23744 3.92678 8.76256 3.92678 8.46967 4.21967Z" fill="currentColor"></path>
            </svg>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
<div class="flex justify-center pt-16">
  <div class="flex flex-col items-center">
    <svg class="text-gray-400 w-16" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewbox="0 0 512 512" xml:space="preserve">
      <g>
        <path d="M454.002,324.104V187.896c16.877-5.176,29.228-20.691,29.228-39.268c0-22.79-18.475-41.257-41.258-41.257            c-10.87,0-20.69,4.292-28.06,11.168L296.125,50.53c0.689-2.991,1.136-6.069,1.136-9.272C297.261,18.468,278.786,0,256.004,0            c-22.782,0-41.258,18.468-41.258,41.258c0,3.203,0.447,6.281,1.136,9.272L98.087,118.54c-7.37-6.876-17.191-11.168-28.062-11.168            c-22.782,0-41.256,18.467-41.256,41.257c0,18.576,12.351,34.091,29.227,39.268v136.208c-16.876,5.176-29.227,20.691-29.227,39.268            c0,22.79,18.474,41.257,41.256,41.257c10.879,0,20.692-4.292,28.062-11.168l117.787,68.01c-0.69,2.991-1.136,6.069-1.136,9.272            c0,22.79,18.475,41.258,41.257,41.258s41.257-18.468,41.257-41.258c0-3.203-0.446-6.288-1.136-9.28l117.788-68.002            c7.37,6.876,17.191,11.168,28.068,11.168c22.783,0,41.258-18.467,41.258-41.257C483.231,344.795,470.879,329.28,454.002,324.104z            M243.967,431.476c-6.054,1.856-11.52,4.965-16.031,9.178l-117.788-68.01c0.689-2.992,1.136-6.077,1.136-9.272            c0-18.576-12.351-34.091-29.228-39.268V187.896c6.054-1.856,11.521-4.965,16.032-9.178l117.787,68.009            c-0.69,2.992-1.136,6.07-1.136,9.273c0,18.576,12.35,34.091,29.228,39.268V431.476z M227.935,225.91l-117.788-68.009            c0.689-2.992,1.136-6.07,1.136-9.273c0-3.203-0.447-6.281-1.136-9.272l117.796-68.01c7.369,6.876,17.19,11.168,28.06,11.168            c10.87,0,20.691-4.292,28.061-11.168l117.787,68.01c-0.689,2.992-1.136,6.069-1.136,9.272c0,3.196,0.447,6.281,1.136,9.273            l-117.803,68.002c-7.37-6.869-17.182-11.16-28.053-11.16S235.305,219.034,227.935,225.91z M429.943,324.104            c-16.877,5.176-29.227,20.691-29.227,39.268c0,3.195,0.447,6.281,1.136,9.272l-117.795,68.01            c-4.519-4.214-9.978-7.323-16.031-9.178V295.268c16.877-5.177,29.227-20.692,29.227-39.268c0-3.203-0.446-6.281-1.136-9.273            l117.796-68.009c4.511,4.214,9.977,7.323,16.031,9.178V324.104z" fill="currentColor"></path>
      </g>
    </svg>
    <p class="mt-4 text-base font-bold text-gray-500"><%= status %>の商品がありません</p>
  </div>
<% end %>

app/views/mypage/items/index.html.erb
<div class="w-full md:w-9/12" id="products">
  <div class="mb-8">
    <h3 class="font-black text-lg mb-4 text-center md:text-2xl md:text-left">出品した商品</h3>
  </div>
  <ul class="flex border-b border-gray-200 w-full md:w-auto">
    <li class="px-4 py-4 border-b-4 border-red-500 text-red-500 font-black md:px-6 text-sm w-1/2 text-center md:text-left md:w-auto">
      <%= link_to "出品中", mypage_items_path, class: "block" %>
    </li>
    <li class="px-4 py-4 text-gray-500 font-normal md:px-6 text-sm w-1/2 text-center md:text-left md:w-auto">
      <%= link_to "取引中", mypage_items_in_progress_path, class: "block" %>
    </li>
    <li class="px-4 py-4 text-gray-500 font-normal md:px-6 text-sm w-1/2 text-center md:text-left md:w-auto">
      <a class="block" href="#">売却済み</a>
    </li>
  </ul>
  <%= render partial: "mypage/items/items", locals: { items: @items, status: "取引中" } %>
  </div>
</div>