config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  devise_scope :user do
    get "users/registrations/complete" => "users/registrations#complete"
  end

  resource :user_information
  resource :user_mobile_phone, only: %i[new create] do
    collection do
      get :verification
      post :verification
    end
  end
  resources :items do
    resources :favorites, only: %i[create destroy], shallow: true
    delete "favorites", to: "favorites#destroy", as: :favorite
    resources :comments, only: %i[create destroy], shallow: true do
      resources :reports, only: %i[new create]
    end
    resources :stripe_payments, only: %i[index new destroy]
    get "stripe_payments/create" => "stripe_payments#create", as: :get_create_stripe_payments
    resource :current_stripe_payment, only: %i[update]
    resources :shipping_addresses
    resource :current_shipping_address, only: %i[update]
    resources :orders, only: %i[new create show], shallow: true do
      resources :messages, only: %i[create]
      member do
        post :ship
      end
      resource :payer_evaluation, only: %i[create]
      resource :seller_evaluation, only: %i[create]
    end
  end

  resources :users, only: %i[show] do
    resources :evaluations, only: %i[index]
  end
  
  get "mypage" => "mypage#index"
  namespace :mypage do
    resources :favorites, only: %i[index destroy]
    resources :items, only: %i[index]
    namespace :items do
      get "in_progress" => "in_progress#index", as: :in_progress
      get "completed" => "completed#index", as: :completed
    end
  end

  resources :notifications, only: %i[index show]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :comment
  belongs_to :report_reason

  validates :body, presence: true
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment

  def new
    @report = @comment.reports.build
    @report.user_id = current_user.id
  end

  def create
    @report = @comment.reports.build(report_params)
    @report.user_id = current_user.id

    if @report.save
      redirect_to item_path(@report.comment.item), notice: "通報の作成に成功しました"
    else
      flash.now.alert = "通報の作成に失敗しました"
      render :new
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:comment_id])
  end

  def report_params
    params.require(:report).permit(:report_reason_id, :body)
  end
end

app/views/reports/new.html.erb
<main class="w-11/12 flex-1 max-w-screen-xl mx-auto bg-white mt-24 pb-24 md:px-8 xl:px-0" id="contents">
  <div class="text-center w-full px-4 bg-white md:w-2/3 lg:w-1/2 mx-auto" id="input">
    <h1 class="font-black mb-8 text-2xl">コメントの報告</h1>
    <%= form_with model: @report, url: comment_reports_path(@comment) do |f| %>
      <%= render partial: "shared/error_messages", locals: { resource: @report } %>
      <div class="text-left">
        <div class="mb-8">
          <%= f.label :report_reason, class: "block text-grey-500 text-sm font-bold mb-2" %>
          <%= f.collection_select :report_reason_id, ReportReason.all, :id, :name, { prompt: true }, class: "w-full text-black p-3 undefined border border-[#CDD6DD]" %>
        </div>
      </div>
      <div class="text-left">
        <div class="mb-8">
          <%= f.label :body, class: "block text-grey-500 text-sm font-bold mb-2" %>
          <%= f.text_area :body, class: "border border-gray-300 rounded py-2 px-3 text-grey-darker h-32 w-full" %>
        </div>
      </div>
      <div class="md:w-10/12 mx-auto">
        <div class="text-center mb-2 flex flex-col space-y-4">
          <%= f.submit "事務局に報告する", class: "text-base font-bold bg-red-500 text-white p-2 w-full block py-4 rounded-sm" %>
        </div>
      </div>
    <% end %>
  </div>
</main>